// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package rozumahouse

type Color struct {
	Rgb *Rgb    `json:"rgb"`
	Hex *string `json:"hex"`
}

type ColorInput struct {
	Rgb *RgbInput `json:"rgb"`
	Hex *string   `json:"hex"`
}

type Device struct {
	Name            *string `json:"name"`
	Room            *string `json:"room"`
	Mac             *string `json:"mac"`
	IP              *string `json:"ip"`
	ChipID          *string `json:"chipId"`
	Model           *string `json:"model"`
	FreeSketchSpace *int    `json:"freeSketchSpace"`
	CoreVersion     *string `json:"coreVersion"`
	SdkVersion      *string `json:"sdkVersion"`
	Info            *Info   `json:"info"`
	Status          []*Led  `json:"status"`
}

type Info struct {
	Actions    []*string `json:"actions"`
	Commands   []*string `json:"commands"`
	Animations []*string `json:"animations"`
	Leds       []*int    `json:"leds"`
	Mode       []*string `json:"mode"`
}

type Led struct {
	ActiveLeds        *int     `json:"activeLeds"`
	Brightness        *int     `json:"brightness"`
	Mode              *string  `json:"mode"`
	Animation         *string  `json:"animation"`
	AnimationDuration *int     `json:"animationDuration"`
	LedOn             *bool    `json:"ledOn"`
	Color             []*Color `json:"color"`
}

type Rgb struct {
	R int `json:"r"`
	G int `json:"g"`
	B int `json:"b"`
}

type RgbInput struct {
	R int `json:"r"`
	G int `json:"g"`
	B int `json:"b"`
}
